-- MySQL Script generated by MySQL Workbench
-- So  3. november 2018, 23:06:43 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema michalstock
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema michalstock
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `michalstock` DEFAULT CHARACTER SET utf8 ;
USE `michalstock` ;

-- -----------------------------------------------------
-- Table `michalstock`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `michalstock`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `michalstock`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `michalstock`.`stock` (
  `idstock` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `origin` VARCHAR(45) NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`idstock`))
ENGINE = InnoDB;

insert into user(username,password) values ("tester","test012");

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
